# Generated by Django 4.0.4 on 2022-04-17 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='balance',
            field=models.FloatField(default=0, verbose_name='Баланс'),
        ),
    ]
