# Generated by Django 3.2.7 on 2022-11-01 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_client_options_alter_operator_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sim',
            old_name='smb_id',
            new_name='smb_slot',
        ),
        migrations.AlterUniqueTogether(
            name='sim',
            unique_together={('client', 'smb_slot')},
        ),
    ]
