# Generated by Django 3.2.7 on 2022-11-01 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20221101_1319'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goip',
            old_name='scheduler',
            new_name='smb_server',
        ),
        migrations.RenameField(
            model_name='sim',
            old_name='bank',
            new_name='smb',
        ),
        migrations.RenameField(
            model_name='simbank',
            old_name='scheduler',
            new_name='smb_server',
        ),
    ]
