# Generated by Django 3.2.7 on 2022-11-01 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20221101_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goip',
            name='smb_server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.simbankscheduler', verbose_name='Scheduler'),
        ),
        migrations.AlterField(
            model_name='simbank',
            name='smb_server',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.simbankscheduler'),
            preserve_default=False,
        ),
    ]
