# Generated by Django 3.2.7 on 2022-12-18 19:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20221218_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='employer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employees', to=settings.AUTH_USER_MODEL, verbose_name='Главный аккаунт'),
        ),
    ]
