# Generated by Django 3.2.7 on 2022-12-29 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20221227_1140'),
    ]

    operations = [
        migrations.AddField(
            model_name='simbankscheduler',
            name='ansible_server_id',
            field=models.IntegerField(default=0, verbose_name='ID сервера на Ansible Server'),
        ),
    ]
