# Generated by Django 3.2.7 on 2023-01-09 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_simbankscheduler_ansible_server_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='simbankscheduler',
            name='install_progress',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Статус установки'),
        ),
    ]
