# Generated by Django 3.2.7 on 2023-01-13 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_simbankscheduler_install_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='simbankscheduler',
            name='rebooting',
            field=models.BooleanField(default=False, verbose_name='Перезагружается'),
        ),
    ]
