# Generated by Django 3.2.7 on 2023-01-23 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_registrationrequest_activated'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='bank_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ID транзакции в банке'),
        ),
    ]
