# Generated by Django 3.2.7 on 2023-01-23 11:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_transaction_bank_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='ID транзакции в банке')),
                ('value', models.FloatField(default=0, verbose_name='Сумма платежа')),
                ('payed', models.BooleanField(default=False, verbose_name='Оплачено')),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'Запрос на оплату',
                'verbose_name_plural': 'Запросы на оплату',
            },
        ),
    ]
