# Generated by Django 3.2.7 on 2023-01-31 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_bankrequest'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ('-id',), 'verbose_name': 'Транзакция', 'verbose_name_plural': 'Транзакции'},
        ),
        migrations.AddField(
            model_name='client',
            name='is_tech_support',
            field=models.BooleanField(default=False, verbose_name='Тех подджержка'),
        ),
    ]
