# Generated by Django 3.2.7 on 2023-01-26 18:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Описание')),
                ('message', models.TextField(verbose_name='Проблема')),
                ('resolved', models.BooleanField(default=False, verbose_name='Решено?')),
                ('dt_create', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Тикет',
                'verbose_name_plural': 'Тикеты',
            },
        ),
        migrations.CreateModel(
            name='TicketMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('is_admin', models.BooleanField(default=False, verbose_name='Сообщение от администратора')),
                ('dt_create', models.DateTimeField(auto_now_add=True, verbose_name='Дата сообщения')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='support.ticket')),
            ],
            options={
                'verbose_name': 'Сообщение тикета',
                'verbose_name_plural': 'Сообщения тикетов',
            },
        ),
    ]
