# Generated by Django 3.2.7 on 2023-01-31 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0002_alter_ticket_client'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ('-id',), 'verbose_name': 'Тикет', 'verbose_name_plural': 'Тикеты'},
        ),
        migrations.AlterModelOptions(
            name='ticketmessage',
            options={'ordering': ('-id',), 'verbose_name': 'Сообщение тикета', 'verbose_name_plural': 'Сообщения тикетов'},
        ),
    ]
